# Generated by Django 5.0.3 on 2024-03-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sub_task',
            new_name='parent_task',
        ),
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
